definitions:
  domain.Track:
    properties:
      group_name:
        type: string
      id:
        type: integer
      link:
        type: string
      realise_date:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
  v1.DeleteResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  v1.ListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Track'
        type: array
      error:
        type: string
    type: object
  v1.TextResponse:
    properties:
      error:
        type: string
      text:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /track/delete:
    delete:
      consumes:
      - application/json
      description: Delete song from storage by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.DeleteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.DeleteResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.DeleteResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.DeleteResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.DeleteResponse'
      summary: Delete song
      tags:
      - track
  /track/list:
    get:
      consumes:
      - application/json
      description: get tracks with filter by query get params. Get parameters is optional
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.ListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ListResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ListResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.ListResponse'
      summary: Get list of song
      tags:
      - track
  /track/text:
    get:
      consumes:
      - application/json
      description: get song text with id separated by choruses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.TextResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.TextResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.TextResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.TextResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.TextResponse'
      summary: Get song text
      tags:
      - track
swagger: "2.0"
